  
export const OKRConstanst ={
    //Lista de OKRS
    LIST_OKRS: "LIST_OKRS",
    LIST_OKRS_SUCCESS: "LIST_OKRS_SUCCESS",
    LIST_OKRS_FAILURE: "LIST_OKRS_FAILURE",

    //Lista de OKRs por ID
    LIST_OKRS_ID:"LIST_OKRS_ID",
    LIST_OKRS_ID_SUCCESS:"LIST_OKRS_ID_SUCCESS",
    LIST_OKRS_ID_FAILURE:"LIST_OKRS_ID_FAILURE",

    //Traer el ultimo usu
    GET_OKR_LAST:"GET_OKR_LAST",
    GET_OKR_LAST_SUCCESS:"GET_OKR_LAST_SUCCESS",
    GET_OKR_LAST_FAILURE:"GET_OKR_LAST_FAILURE",

    GET_ALL_OKRS : "GET_ALL_OKRS",
    GET_ALL_OKRS_SUCCESS: "GET_ALL_OKRS_SUCCESS",
    GET_ALL_OKRS_FAILURE: "GET_ALL_OKRS_FAILURE",
}