export const CalendarTypes = {
   AUTHENTICATED_CALENDAR: '[calendar] authenticated_calendar',
   AUTHENTICATED_CALENDAR_FAILURE: '[calendar] authenticated_calendar_failure',
   AUTHENTICATED_CALENDAR_SUCCESS: '[calendar] authenticated_calendar_success',
   ADD_EVENT: '[calendar] add_event',
   ADD_EVENT_FAILURE: '[calendar] add_event_failure',
   ADD_EVENT_SUCCESS: '[calendar] add_event_success',
   LIST_EVENTS: '[calendar] list_events',
   LIST_EVENTS_FAILURE: '[calendar] list_events_failure',
   LIST_EVENTS_SUCCESS: '[calendar] list_events_success',
   DELETE_EVENT: '[calendar] delete_event',
   DELETE_EVENT_FAILURE: '[calendar] delete_events_failure',
   DELETE_EVENT_SUCCESS: '[calendar] delete_events_success',
   UPDATE_EVENT: '[calendar] update_event',
   UPDATE_EVENT_SUCCESS: '[calendar] update_event_success',
   UPDATE_EVENT_FAILURE: '[calendar] update_event_failure',
   GET_EMAIL_USERS: '[calendar] get_email_users',
   GET_EMAIL_USERS_SUCCESS: '[calendar] get_email_users_success',
   GET_EMAIL_USERS_FAILURE: '[calendar] get_email_users_failure',
}
