export const LOAD_OKRS = '[okrs] okrs'
export const LOAD_OKRS_SUCCESS = '[okrs] okrs success'
export const LOAD_OKRS_FAILURE = '[okrs] okrs failure'
export const ADD_OKRS = '[okrs] add okrs '
export const ADD_OKRS_SUCCESS = '[okrs] add okrs success'
export const ADD_OKRS_FAILURE = '[okrs] add okrs failure'
export const UPDATE_OKRS = '[okrs] update okrs '
export const UPDATE_OKRS_SUCCESS = '[okrs] update okrs success'
export const UPDATE_OKRS_FAILURE = '[okrs] update okrs failure'
export const DELETE_OKRS = '[okrs] delete okrs'
export const DELETE_OKRS_SUCCESS = '[okrs] delete okrs success'
export const DELETE_OKRS_FAILURE = '[okrs] delete okrs failure'
export const GET_OKRS_USER = "GET_OKRS_USER"
export const GET_OKRS_USER_SUCESS = "GET_OKRS_USER_SUCESS"
export const GET_OKRS_USER_FAILURE = "GET_OKRS_USER_FAILURE"